///////////////////////////////////////////////////////////////////////////////
// Untitled1Interfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "Untitled1Services.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_6766D7F3_3908_4D4C_8A3B_39ED7C3EC1E2_INCLUDED_)
#define _TC_TYPE_6766D7F3_3908_4D4C_8A3B_39ED7C3EC1E2_INCLUDED_
struct __declspec(novtable) ITcVnDisplayableImage : public ITcUnknown
{
};
_TCOM_SMARTPTR_TYPEDEF(ITcVnDisplayableImage, IID_ITcVnDisplayableImage);
#endif // !defined(_TC_TYPE_6766D7F3_3908_4D4C_8A3B_39ED7C3EC1E2_INCLUDED_)

///</AutoGeneratedContent>
