///////////////////////////////////////////////////////////////////////////////
// Untitled1Services.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Untitled1 = 0x3F000000;
#define SRVNAME_UNTITLED1 "Untitled1"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_Untitled1CModule1 = {0x0be2f9c4,0x1861,0x4fcd,{0xbe,0x28,0x1d,0xe9,0xb7,0x50,0x57,0x48}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Module1Images 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_Module1oidITcVnImageProvider = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_6766D7F3_3908_4D4C_8A3B_39ED7C3EC1E2_INCLUDED_)
#define _TC_IID_6766D7F3_3908_4D4C_8A3B_39ED7C3EC1E2_INCLUDED_
TCOM_DECL_INTERFACE("6766d7f3-3908-4d4c-8a3b-39ed7c3ec1e2", ITcVnDisplayableImage)
#endif // !defined(_TC_IID_6766D7F3_3908_4D4C_8A3B_39ED7C3EC1E2_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _Module1Images
{
	ITcVnDisplayableImage* ipSrcImageDisp;
	ITcVnDisplayableImage* ipDestImageDisp;
} Module1Images, *PModule1Images;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
