///////////////////////////////////////////////////////////////////////////////
// FirstStepsServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_FirstSteps = 0x3F000000;
#define SRVNAME_FIRSTSTEPS "FirstSteps"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_FirstStepsCFirstStepsVisionModule = {0x0fd50459,0x99fd,0x4351,{0xae,0x52,0x49,0x73,0xa9,0x06,0x72,0xa1}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_FirstStepsVisionModuleImages 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_FirstStepsVisionModuleoidITcVnImageProvider = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_6766D7F3_3908_4D4C_8A3B_39ED7C3EC1E2_INCLUDED_)
#define _TC_IID_6766D7F3_3908_4D4C_8A3B_39ED7C3EC1E2_INCLUDED_
TCOM_DECL_INTERFACE("6766d7f3-3908-4d4c-8a3b-39ed7c3ec1e2", ITcVnDisplayableImage)
#endif // !defined(_TC_IID_6766D7F3_3908_4D4C_8A3B_39ED7C3EC1E2_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _FirstStepsVisionModuleImages
{
	ITcVnDisplayableImage* ipSrcImageDisp;
	ITcVnDisplayableImage* ipDestImageDisp;
} FirstStepsVisionModuleImages, *PFirstStepsVisionModuleImages;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
