///////////////////////////////////////////////////////////////////////////////
// FirstStepsClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "FirstStepsClassFactory.h"
#include "FirstStepsServices.h"
#include "FirstStepsVersion.h"
#include "FirstStepsVisionModule.h"

BEGIN_CLASS_MAP(CFirstStepsClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_FirstSteps, CID_FirstStepsCFirstStepsVisionModule, SRVNAME_FIRSTSTEPS "!CFirstStepsVisionModule", CFirstStepsVisionModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CFirstStepsClassFactory::CFirstStepsClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_FIRSTSTEPS));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(FirstSteps));
#endif //defined(TCDBG_UNIT_VERSION)
}

